# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
owner: Glenda Graff
title: Glenda Graff
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: info@glendagraff.com.au
phone: +61410572601
phone_pretty: 0410 572 601
address: >-
  P.O. Box 464,
  Rose Bay NSW 2029
description: >- # this means to ignore newlines until "baseurl:"
  Whether you are planning a wedding, party or corporate function, Glenda and her team of professionals will ensure that your function is unique, distinct and exceptional.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://glendagraff.com.au/" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: glendagraffevents
facebook_username: Glenda-Graff-Food-Décor-Concepts-951366801563312

markdown: kramdown
theme: minima
plugins:
- jekyll-feed
