---
title: Glenda Graff
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
owner: Glenda Graff
email: info@glendagraff.com.au
phone: 61410572601
phone_pretty: 0410 572 601
address: P.O. Box 464,<br/>Rose Bay NSW 2029
description: Whether you are planning a wedding, party or corporate function, Glenda
  and her team of professionals will ensure that your function is unique, distinct
  and exceptional.
baseurl: ''
url: http://glendagraff.com.au/
instagram_username: glendagraffevents
facebook_username: Glenda-Graff-Food-Décor-Concepts-951366801563312
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
show_excerpts: true
